import { hashText } from '../theory/blocks';
import { splitReference } from './references';
import type { ReferenceData, ReferenceRole } from './types';

// Authored synthetic regression corpus, not researcher-labelled real literature.
// Labels name exact paragraphs; queries and expected labels are fixed, not generated by the retriever.
const corpus: [string, ReferenceRole, [string, string][]][] = [
  ['photon', 'external', [['mass', '광자는 진공에서 정지 질량이 0이다. photon rest mass is zero.'], ['speed', '진공의 빛 속도 c는 299792458 m/s이다. speed of light.']]],
  ['probability', 'external', [['normalization', '확률 정규화 조건은 합계 1이다. probability normalization.'], ['negative', '음수 확률은 표준 확률 공리를 위반한다. negative probability counterexample.']]],
  ['spin', 'external', [['spin', '스핀은 기하학적 회전이 아니다. spin is not geometric rotation.'], ['geometry', '공간의 회전은 기하학적 좌표 변환이다. geometric rotation.']]],
  ['matrix', 'external', [['hermitian', '에르미트 행렬 H = H†의 고윳값은 실수다. Hermitian eigenvalues.'], ['unitary', '유니터리 행렬 U†U = I는 노름을 보존한다. unitary norm.']]],
  ['scope', 'external', [['positive', '양수 실수 x > 0에 대해서만 log(x)를 정의한다. positive real logarithm domain.'], ['boundary', 'x = 0에서는 log(x)가 정의되지 않는다. boundary counterexample.']]],
  ['theorem', 'external', [['t1', '정리 T1: 유한 차원에서 trace(AB) = trace(BA)이다. finite dimensional trace.'], ['infinite', '무한 차원 연산자의 trace에는 추가 수렴 조건이 필요하다. infinite convergence.']]],
  ['thermal', 'external', [['heat', '비열 heat capacity는 온도 변화에 대한 열량의 비다.'], ['absolute', '절대 온도 absolute temperature는 Kelvin으로 나타낸다.']]],
  ['english', 'external', [['entanglement', 'Quantum entanglement is a correlation of a composite state that is not separable.'], ['decoherence', 'Decoherence describes loss of interference through interaction with an environment.']]],
  ['old', 'theory_snapshot', [['old', '과거 버전 V1: 가정 A > 0이면 결과 B다. legacy assumption.']]],
  ['current', 'theory_snapshot', [['current', '현재 버전 V2: 가정 A > 1이면 결과 B다. revised assumption.']]],
  ['memo', 'note', [['memo', '사용자 메모: 질량 관련 추측은 아직 검증하지 않았다. unverified mass conjecture.']]],
  ['secret', 'external', [['secret', 'EXCLUDED_PRIVATE_TOKEN quantum mass photon']]]
];

export interface RetrievalCase {
  id: string;
  category: string;
  split: 'development' | 'holdout';
  query: string;
  expected: string[];
  selected?: string[];
}
type Row = [string, string[], string[]?];
const groups: [string, Row[]][] = [
  ['definition', [
    ['photon rest mass', ['photon:mass']], ['speed of light', ['photon:speed']],
    ['probability normalization', ['probability:normalization']], ['Hermitian eigenvalues', ['matrix:hermitian']],
    ['unitary norm', ['matrix:unitary']], ['heat capacity', ['thermal:heat']],
    ['absolute temperature', ['thermal:absolute']], ['Quantum entanglement', ['english:entanglement']],
    ['Decoherence environment', ['english:decoherence']], ['geometric rotation', ['spin:spin', 'spin:geometry']]
  ]],
  ['korean', [
    ['광자의 질량', ['photon:mass']], ['빛의 속도', ['photon:speed']],
    ['확률의 정규화', ['probability:normalization']], ['음수 확률', ['probability:negative']],
    ['스핀의 회전', ['spin:spin']], ['에르미트 고윳값', ['matrix:hermitian']],
    ['유니터리 노름', ['matrix:unitary']], ['비열 온도', ['thermal:heat']],
    ['절대 온도', ['thermal:absolute']], ['무한 차원의 수렴', ['theorem:infinite']]
  ]],
  ['mixed', [
    ['광자 photon 질량', ['photon:mass']], ['진공 speed c', ['photon:speed']],
    ['확률 normalization', ['probability:normalization']], ['스핀 geometric', ['spin:spin']],
    ['행렬 Hermitian', ['matrix:hermitian']], ['유니터리 U', ['matrix:unitary']],
    ['양수 log domain', ['scope:positive']], ['무한 infinite trace', ['theorem:infinite']],
    ['비열 heat', ['thermal:heat']], ['온도 Kelvin', ['thermal:absolute']]
  ]],
  ['symbol', [
    ['H† 고윳값', ['matrix:hermitian']], ['U†U norm', ['matrix:unitary']],
    ['T1 trace AB', ['theorem:t1']], ['299792458', ['photon:speed']], ['log(x) x = 0', ['scope:boundary']]
  ]],
  ['scope', [
    ['유한 차원 trace 조건', ['theorem:t1']], ['무한 차원 추가 조건', ['theorem:infinite']],
    ['positive real log', ['scope:positive']], ['진공 질량 조건', ['photon:mass']], ['log 정의 경계', ['scope:boundary']]
  ]],
  ['counterexample', [
    ['negative probability', ['probability:negative']], ['boundary counterexample', ['scope:boundary']],
    ['표준 공리 위반', ['probability:negative']], ['x = 0 정의되지', ['scope:boundary']], ['회전 아닌 스핀', ['spin:spin']]
  ]],
  ['version_selection', [
    ['가정 A 결과 B', ['current:current'], ['current']], ['가정 A 결과 B', ['old:old'], ['old']],
    ['revised assumption', ['current:current'], ['current', 'old']], ['legacy assumption', ['old:old'], ['current', 'old']],
    ['unverified mass', ['memo:memo'], ['memo']]
  ]],
  ['no_evidence', [
    ['zzzznevermatches', []], ['unicornontology', []], ['EXCLUDED_PRIVATE_TOKEN', []],
    ['Decoherence', [], ['photon']], ['revised', [], ['old']]
  ]],
  ['cross_language', [
    ['양자 얽힘 비분리 상태', ['english:entanglement'], ['english']],
    ['환경 상호작용에 의한 간섭 소실', ['english:decoherence'], ['english']],
    ['빛 속도', ['photon:speed'], ['english', 'photon']],
    ['복합 상태 상관관계', ['english:entanglement'], ['english']],
    ['탈동조화', ['english:decoherence'], ['english']]
  ]]
];

export const RETRIEVAL_CASES: RetrievalCase[] = groups.flatMap(([category, rows]) => rows.map(([query, expected, selected], index) => ({
  id: `${category}-${index + 1}`, category, query, expected, selected,
  // Fixed query-level split. This is not an unseen-corpus or human evaluation.
  split: index % 3 === 1 ? 'holdout' : 'development'
})));

export async function evaluationCorpus(): Promise<ReferenceData> {
  const data: ReferenceData = { references: [], referenceSpans: [] };
  for (const [id, role, paragraphs] of corpus) {
    const text = `# ${id}\n\n` + paragraphs.map(([, text]) => text).join('\n\n');
    data.references.push({ id, name: `${id}.md`, text, contentHash: await hashText(text), role,
      originVersionId: null, parserVersion: 'text-v1', createdAt: 0 });
    for (const [position, part] of splitReference(text).entries()) {
      const label = paragraphs.find(([, quote]) => part.text.includes(quote))?.[0] ?? 'heading';
      data.referenceSpans.push({ ...part, id: `${id}:${label}`, sourceId: id, position, contentHash: await hashText(part.text) });
    }
  }
  return data;
}
