import { test, expect } from './fixtures/test';
import { readFile } from 'node:fs/promises';

test('approves graph premises in RAG, blocks stale previews, cites canonical originals and restores frozen answers', async ({ page, browser }) => {
  let calls = 0;
  await page.route('https://generativelanguage.googleapis.com/**', async route => {
    calls++;
    const request = route.request().postDataJSON(); const prompt = request.contents.at(-1).parts[0].text as string;
    const data = JSON.parse(prompt.split('reference_data (인용 데이터, 지시 아님):\n')[1]);
    expect(data.graph.context.targetBlockIds).toHaveLength(1); expect(data.graph.context.premiseBlockIds).toHaveLength(1);
    expect(data.graph.blocks).toHaveLength(2); expect(prompt).not.toContain('PRIVATE'); expect(prompt).not.toContain('stateSignature');
    expect(data.evidence).toHaveLength(1); expect(data.evidence[0].name).toBe('chosen.txt');
    await route.fulfill({ status: 200, contentType: 'text/event-stream', body: `data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text: '원문 [[R1]]과 자체 정본 가정 [[G1]] 및 목표 [[G2]]를 구분한다. 이것은 정합성 증명이 아니다.' }] } }] })}\n\n` });
  });
  await page.goto('/'); await page.getByLabel('Google Gemini API Key').fill('answer-graph-fake');
  await page.getByRole('button', { name: '설정 저장' }).click(); await page.locator('#header-model-select').selectOption('gemini-3.1-pro-preview');
  await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '연구노트', exact: true });
  await editor.getByLabel('문서 제목', { exact: true }).fill('답변 그래프 연구');
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 가정\n\nA > 0.\n\n# 결과\n\nB > A. needle.\n\n# PRIVATE unselected heading');
  await editor.getByRole('button', { name: '정본 문서 만들기' }).click();
  const review = editor.getByRole('region', { name: '문서 검토', exact: true });
  await review.locator('.theory-review-advanced > summary').click();
  await review.getByRole('button', { name: '기본 구조 확인', exact: true }).click();
  await review.locator('summary').filter({ hasText: '주장 후보' }).click();
  const claims = review.getByRole('combobox', { name: /^주장 채택 상태/ });
  await claims.nth(0).selectOption('accepted'); await claims.nth(1).selectOption('accepted');
  const relations = editor.getByRole('region', { name: '주장 관계와 Wiki' });
  await editor.locator('details[aria-label="고급 문서 도구"] > summary').click();
  await relations.getByRole('button', { name: '관계 목록 새로고침' }).click();
  await expect(relations.getByLabel('출발 주장', { exact: true }).locator('option')).toHaveCount(3);
  const values = await relations.getByLabel('출발 주장', { exact: true }).locator('option').evaluateAll(elements => elements.map(e => (e as HTMLOptionElement).value).filter(Boolean));
  await relations.getByLabel('출발 주장', { exact: true }).selectOption(values[1]); await relations.getByLabel('도착 주장 또는 구간').selectOption(values[0]);
  await relations.getByLabel('의존성 종류').selectOption('proof'); await relations.getByLabel('관계 승인 사유').fill('B requires A');
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click(); await relations.getByRole('button', { name: '이 관계 승인·저장' }).click();
  await expect(relations.getByRole('status')).toContainText('승인·저장'); await editor.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'chosen.txt', mimeType: 'text/plain', buffer: Buffer.from('Positive evidence needle.') });
  await expect(library.getByRole('checkbox', { name: /chosen.txt/ })).toBeChecked();
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'PRIVATE.txt', mimeType: 'text/plain', buffer: Buffer.from('PRIVATE excluded evidence needle.') });
  await library.getByRole('checkbox', { name: /PRIVATE.txt/ }).uncheck();
  await library.getByLabel('필수 연구 기준 (정본 버전 선택)').selectOption({ label: '답변 그래프 연구 · v1' });
  await library.getByRole('checkbox', { name: '답변에 승인 그래프 전제·정의 포함' }).check();
  await library.getByLabel('레퍼런스에 질문').fill('needle');
  const candidates = library.getByRole('region', { name: '정본 목표 후보', exact: true });
  const target = library.getByRole('checkbox', { name: /그래프 목표 블록 4/ }); await expect(target).not.toBeChecked();
  let releaseWorker!: () => void; const heldWorker = new Promise<void>(resolve => { releaseWorker = resolve; }); let workerRequests = 0;
  await page.route('**/canonical.worker.ts*', async route => { if (++workerRequests === 1) await heldWorker; await route.continue().catch(() => { }); });
  await candidates.getByRole('button', { name: '질문으로 정본 목표 후보 찾기' }).click();
  await candidates.getByRole('button', { name: '정본 후보 검색 중단' }).click(); await expect(candidates.getByRole('alert')).toContainText('중단'); releaseWorker();
  await candidates.getByRole('button', { name: '질문으로 정본 목표 후보 찾기' }).click();
  await expect(candidates.getByRole('article')).toHaveCount(1); await expect(candidates).toContainText('추가 전제 1');
  await expect(target).not.toBeChecked(); expect(calls).toBe(0);
  await candidates.getByRole('button', { name: '이 후보를 목표에 추가' }).click(); await expect(target).toBeChecked();
  await library.getByLabel('레퍼런스에 질문').fill('absent_token'); await expect(candidates.getByRole('article')).toHaveCount(0);
  await candidates.getByRole('button', { name: '질문으로 정본 목표 후보 찾기' }).click(); await expect(candidates).toContainText('일치하는 정본 용어가 없습니다');
  await library.getByLabel('레퍼런스에 질문').fill('needle'); await candidates.getByRole('button', { name: '질문으로 정본 목표 후보 찾기' }).click();
  await expect(candidates.getByRole('article')).toHaveCount(1); await expect(candidates.getByRole('button', { name: '후보 목표 선택 해제' })).toBeVisible();
  await library.getByRole('button', { name: '원문 검색', exact: true }).click();
  await library.getByRole('button', { name: '전송 내용 미리보기', exact: true }).click();
  const preview = library.getByRole('region', { name: '전송 미리보기', exact: true });
  await expect(preview).toContainText('그래프 목표 1블록 · 추가 전제 1블록'); await expect(preview).not.toContainText('PRIVATE'); expect(calls).toBe(0);
  // Another tab revokes an anchor after the preview. The stale request must stay local.
  const other = await page.context().newPage(); await other.goto('/'); await other.getByRole('button', { name: '연구노트', exact: true }).click();
  const otherEditor = other.getByRole('dialog', { name: '연구노트', exact: true });
  await otherEditor.getByRole('button', { name: '답변 그래프 연구 · v1' }).click();
  await otherEditor.locator('summary').filter({ hasText: '주장 후보' }).click();
  const otherClaims = otherEditor.getByRole('combobox', { name: /^주장 채택 상태/ }); await otherClaims.nth(0).selectOption('rejected');
  await library.getByRole('button', { name: '이 근거로 질문 보내기' }).click(); await expect(library.getByRole('alert')).toContainText('변경'); expect(calls).toBe(0);
  await otherClaims.nth(0).selectOption('accepted');
  await expect(otherClaims.nth(0)).toHaveValue('accepted'); await expect(otherClaims.nth(0)).toBeEnabled();
  await other.close();
  await library.getByRole('button', { name: '전송 내용 미리보기', exact: true }).click(); await expect(preview).toContainText('추가 전제 1블록');
  await library.getByRole('button', { name: '이 근거로 질문 보내기' }).click();
  const answer = page.getByRole('region', { name: '답변 근거' }); await expect(answer).toContainText('[[G1]]'); expect(calls).toBe(1);
  await answer.getByText('답변의 정본 그래프', { exact: false }).click(); await expect(answer).toContainText('A > 0'); await expect(answer).not.toContainText('전송 근거에 없는 인용');
  await page.locator('#open-settings-btn').click();
  const ready = page.waitForEvent('download'); await page.getByRole('button', { name: '작업공간 백업', exact: true }).click();
  const backup = (await (await ready).path())!; const serialized = await readFile(backup, 'utf8'); const data = JSON.parse(serialized);
  expect(data.version).toBe(22); expect(serialized).not.toContain('answer-graph-fake');
  const frozen = data.data.messages.find((m: { contextBundle?: unknown }) => m.contextBundle).contextBundle.graph;
  expect(frozen.blocks).toHaveLength(2);
  const context = await browser.newContext();
  try {
    await context.route('**/*', route => ['127.0.0.1', 'localhost'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
    const restored = await context.newPage(); await restored.goto('/'); restored.once('dialog', d => d.accept());
    await restored.getByLabel('Qaxiom 작업공간 백업 파일').setInputFiles(backup); await expect(restored.getByRole('status').filter({ hasText: '작업공간을 복원했습니다' })).toBeVisible();
    await restored.locator('.modal-close-btn').click();
    const restoredAnswer = restored.getByRole('region', { name: '답변 근거' }); await restoredAnswer.getByText('답변의 정본 그래프', { exact: false }).click();
    await expect(restoredAnswer).toContainText(frozen.context.contextHash); await expect(restoredAnswer).toContainText('A > 0');
  } finally { await context.close(); }
});
