import { expect, test } from './fixtures/test';

test('opens project setup before chat and enters document work from the primary sidebar action', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(window, 'showDirectoryPicker', {
      configurable: true,
      value: async () => ({ name: 'research-folder' })
    });
  });
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1, name: 'Projects' })).toBeVisible();
  await expect(page.getByRole('button', { name: '채팅 화면 열기' })).toBeDisabled();
  await page.getByLabel('프로젝트 이름').fill('새 물리 이론');
  await page.getByRole('button', { name: '로컬 폴더 지정' }).click();
  await expect(page.getByText('선택한 폴더: research-folder')).toBeVisible();
  await page.getByRole('button', { name: '채팅 화면 열기' }).click();
  await expect(page.locator('.sidebar-project-card').getByText('새 물리 이론', { exact: true })).toBeVisible();
  await expect(page.locator('.header-project-chip').getByText('새 물리 이론', { exact: true })).toBeVisible();
  await expect(page.locator('.center-document-header .header-project-label')).toHaveJSProperty('tagName', 'DIV');
  await expect(page.getByText('LLM Research Wiki')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '새 연구 문서' })).toBeVisible();
  await expect(page.getByRole('button', { name: '새 대화' })).toBeVisible();
  await expect(page.getByRole('button', { name: '레퍼런스 검색' })).toBeVisible();

  const leftTopBarButton = page.locator('.sidebar-brand-btn');
  await leftTopBarButton.hover();
  await expect.poll(() => leftTopBarButton.evaluate(element => getComputedStyle(element, '::after').opacity)).toBe('1');
  expect(await leftTopBarButton.evaluate(element => getComputedStyle(element, '::after').content)).toContain('프로젝트 관리');

  const centerTopBarButton = page.locator('.center-header-new-btn');
  await centerTopBarButton.hover();
  await expect.poll(() => centerTopBarButton.evaluate(element => getComputedStyle(element, '::after').opacity)).toBe('1');
  expect(await centerTopBarButton.evaluate(element => getComputedStyle(element, '::after').content)).toContain('새 문서');

  const rightTopBarButton = page.locator('.chat-history-toggle-btn');
  await rightTopBarButton.hover();
  await expect.poll(() => rightTopBarButton.evaluate(element => getComputedStyle(element, '::after').opacity)).toBe('1');
  expect(await rightTopBarButton.evaluate(element => getComputedStyle(element, '::after').content)).toContain('대화 기록');
  await expect(page.locator('.chat-title-toggle-btn svg')).toBeVisible();
  await expect(page.locator('.chat-title-toggle-btn span')).toHaveCount(0);
  await expect(page.locator('.chat-title-toggle-btn')).toHaveAttribute('data-tooltip', '제목 변경');
  await expect(page.locator('.chat-panel-header-right > :first-child')).toHaveClass(/chat-title-toggle-btn/);

  await page.getByRole('button', { name: '새 연구 문서' }).click();
  const editor = page.locator('dialog.theory-workspace');
  await expect(editor).toHaveAccessibleName('새 연구 문서');
  await expect(editor.getByLabel('연구 작업 모드')).toHaveCount(0);
  await expect(editor.getByRole('heading', { name: '1. 문서 작성' })).toBeVisible();
  await expect(editor.getByRole('navigation', { name: '정본 문서 목록' })).toHaveCount(0);
  await expect(editor.getByRole('complementary', { name: 'AI 분석과 검토 결과' })).toHaveCount(0);
  await expect(editor.getByRole('button', { name: '문서 저장' })).toBeDisabled();
  await editor.getByLabel('문서 제목', { exact: true }).fill('새 가설');
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 새 가설\n\n내용과 인라인 수식 $a+b$\n\n$$\nE = mc^2\n$$');
  await editor.getByRole('button', { name: '미리보기' }).click();
  const documentPreview = editor.locator('.theory-markdown-preview-pane');
  await expect(editor.getByLabel('미리보기 수식 렌더러')).toHaveValue('katex');
  await expect(documentPreview.locator('.katex')).toHaveCount(2);
  await expect(documentPreview.locator('.katex-display')).toBeVisible();
  await editor.getByLabel('미리보기 수식 렌더러').selectOption('mathjax');
  await expect(documentPreview.locator('mjx-container.MathJax')).toHaveCount(2);
  await expect(documentPreview.locator('mjx-container[display="true"] svg')).toBeVisible();
  await expect(documentPreview.locator('.theory-preview-content')).toHaveCSS('max-width', '860px');
  await expect(documentPreview.locator('mjx-container[display="true"]')).toHaveCSS('border-radius', '10px');
  await editor.getByRole('button', { name: '편집', exact: true }).click();
  await editor.getByRole('button', { name: '문서 저장' }).click();
  await expect(editor).toContainText('v1 저장 완료');
  await expect(editor.getByRole('status').filter({ hasText: 'v1 저장 완료' })).toHaveCount(0, { timeout: 7000 });
  await expect(editor).toHaveAccessibleName('새 가설');
  await expect(editor.getByRole('button', { name: '새 가설 제목 수정' }).locator('.theory-title-edit-affordance')).toBeVisible();
  const aiAnalysisButton = editor.getByRole('complementary', { name: 'AI 분석과 검토 결과' }).getByRole('button', { name: 'AI로 문서 분석' });
  await expect(aiAnalysisButton).toBeVisible();
  await expect(aiAnalysisButton.locator('span')).toHaveCount(0);
  await expect(aiAnalysisButton).toHaveCSS('width', '32px');
  await aiAnalysisButton.hover();
  await expect.poll(() => aiAnalysisButton.evaluate(element => getComputedStyle(element, '::after').opacity)).toBe('1');
  expect(await aiAnalysisButton.evaluate(element => getComputedStyle(element, '::after').content)).toContain('AI 분석');
  await expect(editor.getByRole('region', { name: 'AI 분석 결과' })).toHaveCount(0);
  await expect(editor.locator('.theory-header-actions > button, .theory-top-ai-aside button')).toHaveCount(2);
  await expect(editor.getByRole('button', { name: 'v1 버전 비교' })).toBeVisible();
  await editor.getByRole('button', { name: 'v1 버전 비교' }).click();
  await expect(editor.getByRole('heading', { name: '문서 버전 비교 및 과거 버전 복원' })).toBeVisible();
  await editor.getByRole('button', { name: '창 닫기' }).click();
  await editor.getByRole('button', { name: '현재 문서 연구 기준 편집' }).click();
  await expect(editor.getByRole('heading', { name: '연구 기준 설정 및 AI 후보 제안' })).toBeVisible();
  await editor.getByRole('button', { name: '창 닫기' }).click();
  await expect(editor.getByRole('button', { name: '프로젝트 자료·문서 관리' })).toHaveCount(0);
  await expect(editor.getByRole('button', { name: '문서 삭제' })).toHaveCount(0);
  await expect(editor.getByRole('button', { name: '새 연구 문서' })).toHaveCount(0);
  await expect(editor.getByRole('button', { name: '닫기', exact: true })).toHaveCount(0);
  await expect(editor.locator('.theory-btn-close')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '새 가설 v1' })).toBeVisible();
  await editor.getByLabel('문서 본문 (Markdown)').fill('아직 저장하지 않은 수정');
  await page.getByRole('button', { name: '새 가설 문서 삭제' }).click();
  const deleteDialog = page.getByRole('dialog', { name: '연구 문서를 삭제할까요?' });
  await expect(deleteDialog.getByRole('alert')).toContainText('저장되지 않은 변경사항');
  await expect(deleteDialog.getByRole('button', { name: '문서 삭제' })).toBeDisabled();
  await deleteDialog.getByRole('button', { name: '취소' }).click();
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 새 가설\n\n내용과 인라인 수식 $a+b$\n\n$$\nE = mc^2\n$$');
  await page.getByRole('button', { name: '새 가설 문서 삭제' }).click();
  await expect(deleteDialog).toContainText('버전 1개');
  await deleteDialog.getByRole('button', { name: '취소' }).click();
  await expect(page.getByRole('button', { name: '새 가설 v1' })).toBeVisible();
  await page.getByRole('button', { name: '새 가설 문서 삭제' }).click();
  await deleteDialog.getByRole('button', { name: '문서 삭제' }).click();
  await expect(page.getByRole('button', { name: '새 가설 v1' })).toHaveCount(0);
  await expect(page.getByText('아직 만든 연구 문서가 없습니다.')).toBeVisible();
  await page.reload();
  await expect(page.locator('main.project-start[role="status"]')).toHaveCount(0);
  const projectSetup = page.getByRole('heading', { level: 1, name: 'Projects' });
  await expect(projectSetup).toBeVisible();
  await expect(page.getByRole('region', { name: 'Projects' })).toContainText('새 물리 이론');
  await expect(page.getByRole('region', { name: 'Projects' })).toContainText('research-folder');
});
