import { expect, test } from './fixtures/test';
import { readFile } from 'node:fs/promises';

test('previews mandatory research criteria, parent expansion and every budget omission before sending', async ({ page }) => {
  let payload = '', calls = 0;
  await page.route('https://generativelanguage.googleapis.com/**', async route => {
    calls++; payload = route.request().postData() || '';
    await route.fulfill({ status: 200, contentType: 'text/event-stream', body: `data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text: '조건부 결과 [[R1]]' }] } }] })}\n\n` });
  });
  await page.goto('/');
  await page.getByLabel('Google Gemini API Key').fill('assembly-e2e-key');
  await page.getByRole('button', { name: '설정 저장' }).click();
  await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '연구노트', exact: true });
  await editor.getByLabel('문서 제목', { exact: true }).fill('필수 전제 연구');
  await editor.getByLabel('문서 본문 (Markdown)').fill('CANONICAL_BODY_NOT_SENT');
  await editor.locator('summary').click();
  await editor.getByLabel('가정·공리', { exact: true }).fill('MANDATORY_UNRANKED x > 0');
  await editor.getByRole('button', { name: '정본 문서 만들기' }).click();
  await expect(editor.getByRole('status')).toContainText('v1 저장 완료');
  await editor.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  const text = '# 부모 절\n\n' + Array.from({ length: 12 }, (_, i) => i === 10 ? 'uniqueneedle 결론' : `parent-paragraph-${i}`).join('\n\n');
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'parents.md', mimeType: 'text/markdown', buffer: Buffer.from(text) });
  await expect(library.getByRole('status')).toContainText('로컬에 저장');
  await library.getByLabel('필수 연구 기준 (정본 버전 선택)').selectOption({ label: '필수 전제 연구 · v1' });
  await library.getByLabel('레퍼런스에 질문').fill('uniqueneedle');
  await library.getByRole('button', { name: '원문 검색', exact: true }).click();
  await expect(library.getByRole('status')).toContainText('검색 결과');
  await library.getByRole('button', { name: '전송 내용 미리보기' }).click();
  const preview = library.getByRole('region', { name: '전송 미리보기' });
  await expect(preview).toContainText('MANDATORY_UNRANKED');
  await expect(preview).toContainText('부모 문맥 추가 7개 · 예산 초과로 제외 5개');
  await expect(preview.locator('li')).toHaveCount(5);
  await expect(preview).toContainText('비어 있는 항목: purpose');
  expect(calls).toBe(0);
  await library.getByLabel('필수 연구 기준 (정본 버전 선택)').selectOption('');
  await expect(preview).toHaveCount(0);
  await library.getByLabel('필수 연구 기준 (정본 버전 선택)').selectOption({ label: '필수 전제 연구 · v1' });
  await library.getByRole('button', { name: '전송 내용 미리보기' }).click();
  await library.getByRole('button', { name: '이 근거로 질문 보내기' }).click();
  await expect(page.getByRole('region', { name: '답변 근거' })).toContainText('parents.md');
  expect(calls).toBe(1);
  expect(payload).toContain('MANDATORY_UNRANKED');
  expect(payload).toContain('omittedSpanIds');
  expect(payload).toContain('parent-paragraph-0');
  expect(payload).not.toContain('parent-paragraph-11');
  expect(payload).not.toContain('CANONICAL_BODY_NOT_SENT');
  await page.reload();
  const evidence = page.getByRole('region', { name: '답변 근거' });
  await evidence.locator('summary').click();
  await expect(evidence).toContainText('MANDATORY_UNRANKED');
  await expect(evidence).toContainText('예산상 미전송 5개');
});

test('searches selected text references, previews transmission, cites originals and restores them in a fresh profile', async ({ page, browser }) => {
  let payload = '';
  let calls = 0;
  await page.route('https://generativelanguage.googleapis.com/**', async route => {
    calls++;
    payload = route.request().postData() || '';
    // First request fails to exercise retry with the same frozen evidence.
    if (calls === 1) { await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '일시적 테스트 오류' } }) }); return; }
    await route.fulfill({ status: 200, contentType: 'text/event-stream', body: `data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text: '광자의 질량은 0이다. [[R1]] 잘못된 인용 [[R999]]' }] } }] })}\n\n` });
  });
  await page.goto('/');
  await page.getByLabel('Google Gemini API Key').fill('reference-e2e-key');
  await page.getByRole('button', { name: '설정 저장' }).click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'excluded.txt', mimeType: 'text/plain', buffer: Buffer.from('광자 EXCLUDED_SECRET_TEXT') });
  await expect(library.getByRole('status')).toContainText('로컬에 저장');
  await library.getByRole('checkbox', { name: /excluded.txt/ }).uncheck();
  const source = '# 광자\r\n\r\n광자는 질량이 없다. photon mass is zero.\r\n\r\n다른 원문 문단.';
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'photon.md', mimeType: 'text/markdown', buffer: Buffer.from(source) });
  await expect(library.getByRole('status')).toContainText('로컬에 저장');
  await library.getByLabel('레퍼런스에 질문').fill('광자의 질량');
  await library.getByRole('button', { name: '원문 검색', exact: true }).click();
  await expect(library.getByRole('status')).toContainText('검색 결과');
  await expect(library.getByRole('region', { name: '검색 근거' })).not.toContainText('EXCLUDED_SECRET_TEXT');
  await library.getByRole('button', { name: '전송 내용 미리보기' }).click();
  await expect(library.getByRole('region', { name: '전송 미리보기' })).toContainText('photon mass is zero');
  expect(calls).toBe(0);
  await library.getByRole('button', { name: '이 근거로 질문 보내기' }).click();
  await expect(page.getByRole('alert')).toContainText('일시적 테스트 오류');
  const firstPayload = JSON.parse(payload);
  await page.getByRole('button', { name: '다시 시도', exact: true }).click();
  await expect(page.getByRole('region', { name: '답변 근거' })).toContainText('전송 근거에 없는 인용: R999');
  expect(calls).toBe(2);
  expect(JSON.parse(payload)).toEqual(firstPayload);
  expect(payload).toContain('photon mass is zero');
  expect(payload).not.toContain('EXCLUDED_SECRET_TEXT');
  expect(payload).not.toContain('excluded.txt');
  await page.getByRole('button', { name: /\[\[R1\]\].*원문 보기/ }).click();
  const sourceDialog = page.getByRole('dialog', { name: '인용 원문: photon.md' });
  await expect(sourceDialog.locator('mark')).toContainText('광자는 질량');
  await expect(sourceDialog.getByLabel('레퍼런스 전체 원문')).toContainText('다른 원문 문단');
  await sourceDialog.getByRole('button', { name: '닫기', exact: true }).click();

  const mdReady = page.waitForEvent('download');
  await page.getByRole('button', { name: '내보내기', exact: true }).click();
  const markdown = await readFile((await (await mdReady).path())!, 'utf8');
  expect(markdown).toContain('전송한 원문 근거');
  expect(markdown).toContain('photon mass is zero');
  await page.locator('#open-settings-btn').click();
  const backupReady = page.waitForEvent('download');
  await page.getByRole('button', { name: '작업공간 백업', exact: true }).click();
  const backup = (await (await backupReady).path())!;
  const other = await browser.newContext();
  try {
    const restored = await other.newPage();
    await restored.goto('/');
    await expect(restored.getByRole('heading', { name: '연구 AI 환경 설정 (BYOK)' })).toBeVisible();
    restored.once('dialog', dialog => dialog.accept());
    await restored.getByLabel('Qaxiom 작업공간 백업 파일').setInputFiles(backup);
    await expect(restored.getByRole('status').filter({ hasText: '작업공간을 복원했습니다' })).toBeVisible();
    await restored.locator('.modal-close-btn').click();
    await restored.reload();
    await expect(restored.getByRole('heading', { name: '연구 AI 환경 설정 (BYOK)' })).toBeVisible();
    await restored.locator('.modal-close-btn').click();
    await restored.getByRole('button', { name: /\[\[R1\]\].*원문 보기/ }).click();
    await expect(restored.getByRole('dialog', { name: '인용 원문: photon.md' }).locator('mark')).toContainText('광자는 질량');
  } finally { await other.close(); }
  await page.locator('.modal-close-btn').click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const reopened = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  page.once('dialog', dialog => dialog.accept());
  await reopened.getByRole('button', { name: '등록 자료 삭제: photon.md' }).click();
  await expect(reopened.getByRole('alert')).toContainText('사용 중');
  await expect(reopened.getByRole('button', { name: '등록 자료 삭제: photon.md' })).toBeVisible();
});

test('deletes only an unused reference after explicit confirmation', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Google Gemini API Key').fill('unused-reference-test-key');
  await page.getByRole('button', { name: '설정 저장' }).click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'unused.md', mimeType: 'text/markdown', buffer: Buffer.from('# 미사용 원문\n\n검색 전에 삭제') });
  await expect(library.getByRole('status')).toContainText('로컬에 저장');
  page.once('dialog', dialog => dialog.dismiss());
  await library.getByRole('button', { name: '등록 자료 삭제: unused.md' }).click();
  await expect(library.getByRole('button', { name: '등록 자료 삭제: unused.md' })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await library.getByRole('button', { name: '등록 자료 삭제: unused.md' }).click();
  await expect(library.getByRole('status')).toContainText('사용되지 않은 자료를 삭제했습니다');
  await expect(library.getByRole('button', { name: '등록 자료 삭제: unused.md' })).toHaveCount(0);
  await library.getByRole('button', { name: '닫기', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  await expect(page.getByRole('button', { name: '등록 자료 삭제: unused.md' })).toHaveCount(0);
});

test('invalidates preview when query or scope changes and rejects unsupported uploads', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '연구 AI 환경 설정 (BYOK)' })).toBeVisible();
  await page.locator('.modal-close-btn').click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'data.bin', mimeType: 'application/octet-stream', buffer: Buffer.from('binary') });
  await expect(library.getByRole('alert')).toContainText('TXT 파일만 지원');
  await library.getByLabel('첨부 문서 종류').selectOption('theory_snapshot');
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'own.md', mimeType: 'text/markdown', buffer: Buffer.from('나의 가정 질량') });
  await expect(library.getByRole('status')).toContainText('로컬에 저장');
  await library.getByLabel('레퍼런스에 질문').fill('질량');
  await library.getByRole('button', { name: '원문 검색', exact: true }).click();
  await expect(library.getByRole('status')).toContainText('검색 결과');
  await library.getByRole('button', { name: '전송 내용 미리보기' }).click();
  await expect(library.getByRole('region', { name: '전송 미리보기' })).toContainText('자체 문서 — 외부 증거 아님');
  await expect(library.getByRole('button', { name: '이 근거로 질문 보내기' })).toBeDisabled();
  await library.getByLabel('레퍼런스에 질문').fill('없는 용어');
  await expect(library.getByRole('region', { name: '전송 미리보기' })).toHaveCount(0);
  await library.getByRole('button', { name: '원문 검색', exact: true }).click();
  await expect(library.getByRole('status')).toContainText('일치하는 원문이 없습니다');
  await library.getByRole('checkbox', { name: /own.md/ }).uncheck();
  await expect(library.getByRole('button', { name: '원문 검색', exact: true })).toBeDisabled();
});
