import { test, expect } from './fixtures/test';
import { readFile } from 'node:fs/promises';

test('approves selected reference relations, explores originals/backlinks, exports a Wiki and restores history without API keys', async ({ page, browser }) => {
  await page.goto('/'); await page.locator('.modal-close-btn').click();
  await page.getByRole('button', { name: '레퍼런스 검색', exact: true }).click();
  const library = page.getByRole('dialog', { name: '레퍼런스 검색', exact: true });
  await library.getByLabel('레퍼런스 파일', { exact: true }).setInputFiles({ name: 'external.txt', mimeType: 'text/plain', buffer: Buffer.from('Independent observation: B is positive when A is positive.') });
  await expect(library.getByRole('checkbox', { name: /external.txt/ })).toBeChecked();
  await library.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '연구노트', exact: true });
  await editor.getByLabel('문서 제목', { exact: true }).fill('승인형 관계 연구');
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 가정\n\nA is positive.\n\n# 결과\n\nB is positive.');
  await editor.getByRole('button', { name: '정본 문서 만들기' }).click();
  const review = editor.getByRole('region', { name: '문서 검토', exact: true });
  await review.locator('.theory-review-advanced > summary').click();
  await review.getByRole('button', { name: '기본 구조 확인', exact: true }).click();
  await review.locator('summary').filter({ hasText: '주장 후보' }).click();
  const acceptance = review.getByRole('combobox', { name: /^주장 채택 상태/ });
  await expect(acceptance).toHaveCount(2);
  await acceptance.nth(0).selectOption('accepted'); await acceptance.nth(1).selectOption('accepted');
  const relations = editor.getByRole('region', { name: '주장 관계와 Wiki' });
  await editor.locator('details[aria-label="고급 문서 도구"] > summary').click();
  await relations.getByRole('button', { name: '관계 목록 새로고침' }).click();
  await expect(relations.getByLabel('출발 주장', { exact: true }).locator('option')).toHaveCount(3);
  const choices = await relations.getByLabel('출발 주장', { exact: true }).locator('option').evaluateAll(elements => elements.map(e => (e as HTMLOptionElement).value).filter(Boolean));
  expect(choices).toHaveLength(2);
  await relations.getByLabel('출발 주장', { exact: true }).selectOption(choices[1]);
  await relations.getByLabel('연결 대상 종류').selectOption('reference');
  await relations.getByLabel('연결할 레퍼런스').selectOption({ label: 'external.txt · external' });
  const span = await relations.getByLabel('도착 주장 또는 구간').locator('option').nth(1).getAttribute('value');
  await relations.getByLabel('도착 주장 또는 구간').selectOption(span!);
  await relations.getByLabel('외부 대조 분류').selectOption('different_scope');
  await relations.getByLabel('자체 주장 가정·정의·범위').fill('모든 양수 A에 대한 연구 주장');
  await relations.getByLabel('원문 결과의 가정·정의·범위').fill('측정된 한정된 A 범위');
  await relations.getByLabel('관계 승인 사유').fill('공통 조건과 측정 범위를 분리해 대조한다.');
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
  await expect(relations.getByRole('region', { name: '관계 승인 미리보기' })).toContainText('Independent observation');
  await relations.getByLabel('관계 승인 사유').fill('범위 변경은 미리보기를 무효화한다.');
  await expect(relations.getByRole('region', { name: '관계 승인 미리보기' })).toHaveCount(0);
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
  await relations.getByRole('button', { name: '이 관계 승인·저장' }).click();
  await expect(relations.getByRole('status')).toContainText('승인·저장');
  await expect(relations.getByRole('region', { name: '승인 관계 이력' })).toContainText('different_scope');
  await relations.getByLabel('Wiki 주장', { exact: true }).selectOption(choices[1]);
  await expect(relations.getByRole('region', { name: 'Research Wiki', exact: true })).toContainText('출발 1');
  await relations.getByRole('button', { name: '주장 원문 블록 확인' }).click();
  await expect(relations.getByLabel('Wiki 주장 전체 블록')).toContainText('B is positive');
  await relations.getByRole('button', { name: '관계 근거 원문: external.txt' }).click();
  const original = page.getByRole('dialog', { name: '인용 원문: external.txt' });
  await expect(original.getByLabel('레퍼런스 전체 원문')).toContainText('Independent observation');
  await original.getByRole('button', { name: '닫기', exact: true }).click();
  const wikiDownload = page.waitForEvent('download'); await relations.getByRole('button', { name: 'Research Wiki 내보내기' }).click();
  const wiki = await readFile((await (await wikiDownload).path())!, 'utf8');
  expect(wiki).toContain('different_scope'); expect(wiki).toContain('external.txt'); expect(wiki).toContain('정합성 보증이 아닙니다');
  await relations.getByLabel('관계 철회 사유').fill('범위 판단을 다시 검토한다.');
  await relations.getByRole('button', { name: '이 관계 철회' }).click();
  await expect(relations.getByRole('region', { name: '승인 관계 이력' })).toContainText('사용자 철회');
  await expect(relations.getByRole('region', { name: 'Research Wiki', exact: true })).toContainText('출발 0');
  await editor.getByRole('button', { name: '닫기', exact: true }).click();
  await page.locator('#open-settings-btn').click();
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '작업공간 백업', exact: true }).click();
  const backup = (await (await download).path())!; const data = JSON.parse(await readFile(backup, 'utf8'));
  expect(data.version).toBe(22); expect(data.data.researchRelations).toHaveLength(1); expect(data.data.researchRelations[0].retractionNote).toContain('범위 판단');
  const context = await browser.newContext();
  try {
    await context.route('**/*', route => { const url = new URL(route.request().url()); return ['127.0.0.1', 'localhost'].includes(url.hostname) ? route.continue() : route.abort(); });
    const restored = await context.newPage(); await restored.goto('/'); restored.once('dialog', dialog => dialog.accept());
    await restored.getByLabel('Qaxiom 작업공간 백업 파일').setInputFiles(backup);
    await expect(restored.getByRole('status').filter({ hasText: '작업공간을 복원했습니다' })).toBeVisible();
    await restored.locator('.modal-close-btn').click(); await restored.getByRole('button', { name: '연구노트', exact: true }).click();
    const restoredEditor = restored.getByRole('dialog', { name: '연구노트', exact: true });
    await restoredEditor.getByRole('button', { name: '승인형 관계 연구 · v1' }).click();
    await restoredEditor.locator('details[aria-label="고급 문서 도구"] > summary').click();
    await expect(restoredEditor.getByRole('region', { name: '승인 관계 이력' })).toContainText('사용자 철회');
    await expect(restoredEditor.getByRole('region', { name: '승인 관계 이력' })).toContainText('different_scope');
  } finally { await context.close(); }
});

test('shows approved proof cycles and backlinks, invalidates dirty previews and keeps prior-version relations stale', async ({ page }) => {
  await page.goto('/'); await page.locator('.modal-close-btn').click();
  await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '연구노트', exact: true });
  await editor.getByLabel('문서 제목', { exact: true }).fill('순환 관계');
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 가정\n\nA > 0.\n\n# 결과\n\nB > A.');
  await editor.getByRole('button', { name: '정본 문서 만들기' }).click();
  const review = editor.getByRole('region', { name: '문서 검토', exact: true });
  await review.locator('.theory-review-advanced > summary').click();
  await review.getByRole('button', { name: '기본 구조 확인', exact: true }).click();
  await review.locator('summary').filter({ hasText: '주장 후보' }).click();
  const acceptance = review.getByRole('combobox', { name: /^주장 채택 상태/ });
  await acceptance.nth(0).selectOption('accepted'); await acceptance.nth(1).selectOption('accepted');
  const relations = editor.getByRole('region', { name: '주장 관계와 Wiki' });
  await editor.locator('details[aria-label="고급 문서 도구"] > summary').click();
  await relations.getByRole('button', { name: '관계 목록 새로고침' }).click();
  await expect(relations.getByLabel('출발 주장', { exact: true }).locator('option')).toHaveCount(3);
  const options = await relations.getByLabel('출발 주장', { exact: true }).locator('option').evaluateAll(elements => elements.map(e => (e as HTMLOptionElement).value).filter(Boolean));
  await relations.getByLabel('의존성 종류').selectOption('proof');
  await relations.getByLabel('관계 승인 사유').fill('명시한 증명 의존성');
  for (const [from, to] of [[options[0], options[1]], [options[1], options[0]]]) {
    await relations.getByLabel('출발 주장', { exact: true }).selectOption(from);
    await relations.getByLabel('도착 주장 또는 구간').selectOption(to);
    await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
    await relations.getByRole('button', { name: '이 관계 승인·저장' }).click();
    await expect(relations.getByRole('status')).toContainText('승인·저장');
  }
  await relations.getByLabel('Wiki 주장', { exact: true }).selectOption(options[0]);
  await expect(relations.getByRole('region', { name: 'Research Wiki', exact: true })).toContainText('역참조 1');
  await expect(relations.getByRole('alert')).toContainText('순환 후보 2개');
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
  await editor.getByLabel('문서 제목', { exact: true }).fill('순환 관계 수정');
  await expect(relations.getByRole('region', { name: '관계 승인 미리보기' })).toHaveCount(0);
  await editor.getByRole('button', { name: '새 버전 저장' }).click();
  await expect(editor.getByRole('status').filter({ hasText: 'v2 저장 완료' })).toBeVisible();
  await expect(relations.getByRole('region', { name: '승인 관계 이력' })).toContainText('오래된 버전 — 재확인 필요');
  await expect(relations.getByRole('region', { name: 'Research Wiki', exact: true })).toContainText('역참조 0');
  await expect(relations.getByRole('alert')).toHaveCount(0);
});
