import { test, expect } from './fixtures/test';
import { readFile } from 'node:fs/promises';

test('previews approved premises separately, sends only frozen selected graph and reports actual checked blocks', async ({ page }) => {
  let calls = 0;
  await page.route('https://generativelanguage.googleapis.com/**', async route => {
    calls++;
    const prompt = route.request().postDataJSON().contents.at(-1).parts[0].text as string;
    const input = JSON.parse(prompt.split('원문이다:\n')[1]);
    expect(input.graphContext.targetBlockIds).toHaveLength(1);
    expect(input.graphContext.premiseBlockIds).toHaveLength(1);
    expect(input.graphContext.relationSnapshots).toHaveLength(1);
    expect(input.blocks).toHaveLength(2); expect(prompt).not.toContain('stateSignature');
    const result = { checkedBlockIds: input.graphContext.targetBlockIds, limitations: [], claims: [], issues: [] };
    await route.fulfill({ status: 200, contentType: 'text/event-stream', body: `data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text: JSON.stringify(result) }] } }] })}\n\n` });
  });
  await page.goto('/'); await page.getByLabel('Google Gemini API Key').fill('graph-test-key');
  await page.getByRole('button', { name: '설정 저장' }).click();
  await page.locator('#header-model-select').selectOption('gemini-3.1-pro-preview');
  await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '연구노트', exact: true });
  await editor.getByLabel('문서 제목', { exact: true }).fill('전제 확장 검토');
  await editor.getByLabel('문서 본문 (Markdown)').fill('# 가정\n\nA > 0.\n\n# 결과\n\nB > A.');
  await editor.getByRole('button', { name: '정본 문서 만들기' }).click();
  const review = editor.getByRole('region', { name: '문서 검토', exact: true });
  await review.locator('.theory-review-advanced > summary').click();
  await review.getByRole('button', { name: '기본 구조 확인', exact: true }).click();
  await review.locator('summary').filter({ hasText: '주장 후보' }).click();
  const acceptance = review.getByRole('combobox', { name: /^주장 채택 상태/ });
  await acceptance.nth(0).selectOption('accepted'); await acceptance.nth(1).selectOption('accepted');
  const relations = editor.getByRole('region', { name: '주장 관계와 Wiki' });
  await editor.locator('details[aria-label="고급 문서 도구"] > summary').click();
  await relations.getByRole('button', { name: '관계 목록 새로고침' }).click();
  await expect(relations.getByLabel('출발 주장', { exact: true }).locator('option')).toHaveCount(3);
  const options = await relations.getByLabel('출발 주장', { exact: true }).locator('option').evaluateAll(elements => elements.map(e => (e as HTMLOptionElement).value).filter(Boolean));
  await relations.getByLabel('출발 주장', { exact: true }).selectOption(options[1]);
  await relations.getByLabel('도착 주장 또는 구간').selectOption(options[0]);
  await relations.getByLabel('의존성 종류').selectOption('proof');
  await relations.getByLabel('관계 승인 사유').fill('B 증명에는 A 가정이 필요하다.');
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
  await relations.getByRole('button', { name: '이 관계 승인·저장' }).click();
  await expect(relations.getByRole('status')).toContainText('승인·저장');
  await review.getByRole('checkbox', { name: /문단 1/ }).uncheck();
  await review.getByRole('checkbox', { name: /문단 2/ }).uncheck();
  await review.getByRole('checkbox', { name: /문단 3/ }).uncheck();
  await review.getByRole('checkbox', { name: '승인 관계의 전제·정의도 포함' }).check();
  await review.getByRole('button', { name: '선택 범위 분할 검토 계획 저장' }).click();
  await expect(review).toContainText('승인 그래프 전제 포함');
  await review.getByText('분할 구간별 필수 문맥', { exact: true }).click();
  await expect(review).toContainText('구간 1: 목표 1 · 추가 전제 1');
  await review.getByRole('checkbox', { name: '승인 관계의 전제·정의도 포함' }).uncheck();
  await review.getByRole('button', { name: '다음 미검사 구간 선택' }).click();
  await expect(review.getByRole('checkbox', { name: '승인 관계의 전제·정의도 포함' })).toBeChecked();
  await review.getByRole('button', { name: '검토 전송 미리보기', exact: true }).click();
  const preview = review.getByRole('region', { name: '검토 전송 미리보기' });
  await expect(preview).toContainText('목표 1블록 · 추가 전제 1블록');
  await expect(preview).toContainText('A > 0'); expect(calls).toBe(0);
  await relations.getByLabel('관계 철회 사유').fill('미리보기 후 관계를 변경한다.');
  await relations.getByRole('button', { name: '이 관계 철회' }).click();
  await expect(relations.getByRole('region', { name: '승인 관계 이력' })).toContainText('사용자 철회');
  await review.getByRole('button', { name: '이 범위로 LLM 검토 실행' }).click();
  await expect(review.getByRole('alert')).toContainText('변경'); expect(calls).toBe(0);
  await expect(review).toContainText('사용 0/3회');
  await relations.getByRole('button', { name: '관계 승인 미리보기', exact: true }).click();
  await relations.getByRole('button', { name: '이 관계 승인·저장' }).click();
  await expect(relations.getByRole('status')).toContainText('승인·저장');
  await review.getByRole('button', { name: '검토 전송 미리보기', exact: true }).click();
  await expect(review.getByRole('alert')).toContainText('계획'); expect(calls).toBe(0);
  await review.getByRole('button', { name: '선택 범위 분할 검토 계획 저장' }).click();
  await review.getByRole('button', { name: '다음 미검사 구간 선택' }).click();
  await review.getByRole('button', { name: '검토 전송 미리보기', exact: true }).click();
  await expect(preview).toContainText('목표 1블록 · 추가 전제 1블록');
  await review.getByRole('button', { name: '이 범위로 LLM 검토 실행' }).click();
  await expect(review).toContainText('사용 1/3회');
  const result = review.getByRole('article').filter({ hasText: 'AI 내용·논리 검토' });
  await expect(result).toContainText('문단 1/4개 확인'); await expect(result).toContainText('판단 자료 부족');
  await expect(review).toContainText('남은 0구간');
  await result.getByText('전송 당시 승인 그래프', { exact: false }).click();
  await expect(result).toContainText('targetBlockIds');
  const download = page.waitForEvent('download'); await result.getByRole('button', { name: '검토 보고서 내보내기' }).click();
  const report = await readFile((await (await download).path())!, 'utf8');
  expect(report).toContain('premiseBlockIds'); expect(report).not.toContain('graph-test-key');
  expect(calls).toBe(1);
  await page.reload(); await page.getByRole('button', { name: '연구노트', exact: true }).click();
  const reopened = page.getByRole('dialog', { name: '연구노트', exact: true });
  await reopened.getByRole('button', { name: '전제 확장 검토 · v1' }).click();
  await expect(reopened).toContainText('전송 당시 승인 그래프');
  await expect(reopened).toContainText('승인 그래프 전제 포함');
  await expect(reopened).toContainText('남은 0구간');
});
